version: '3.8'

services:
  api:
    container_name: architech_api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1